version: "3.8"

services:
  mongo:
    container_name: bob.db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./config/init-db.js:/docker-entrypoint-initdb.d/init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: bob-dev

  mongo-express:
    container_name: bob.db.ui
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
